on: [pull_request]

jobs:
  code-review:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   pull-requests: write
    #   issues: write
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: sshnaidm/gpt-code-review-action@v1.0
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          post-if-error: true
          # github-token: ${{ secrets.MYGITHUBTOKEN }}
